### PR TITLE
Move JDT down to JLS3 for better compatibility

### PR DESCRIPTION
**Pull request by seamusmac**

### CODE REVIEW

**Comment by branflake2267** [comment]
Nice job thank you!

**Comment by seamusmac** [comment]
Thanks for merging. 
Can you let me know when you send this off to staging and a build a snapshot, and I can do some more testing on it from there. Cheers.

**Comment by branflake2267** [comment]
I'm working on it now. It looks like I have to update the targets first, once I do that I'll push it off to staging for testing.

**Comment by seamusmac** [comment]
Thats great. No crazy rush, good to know its on the way.

**Comment by branflake2267** [comment]
I've been meaning to update the default gwt version to 2.8.2 so I've got that going on. The targets have been updated and it's building now. I'll close and make a note in this PR when it's ready. https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/376

**Pull request merged**
