### PR TITLE
Unified the libs folder names.

### PR DESCRIPTION
**Pull request by keinhaar**
Renamed all "lib" folders to "libs", to be unique across all plugins.

### CODE REVIEW

**Comment by protoism** [comment]
@keinhaar, I wonder, if we should just remove the binary artifacts from the repository, and go the maven way.

For sure .classpath files and .project files can be recreated correctly by a simple maven import.
For artifacts, it is a bit more tricky, but it should be possible.

Managing dependencies the way we're doing now is a bit of a nightmare

**Comment by keinhaar** [comment]
Maybe, but i did not want to change the way things are done today. Just cleaning up.
If you can do it with maven, feel free to do it. I don't use maven very much. So i can't do that.

**Comment by protoism** [comment]
Hi @keinhaar, I marked this for 4.1, as this PR is really cosmetic, i.e. no bug fixed, no real improvement... nothing that we "forgot" on 4.0.0. 
I still wonder if we have to go all in with maven and remove all artifacts, but it requires time and patience...
So.. if we fix https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/454  this PR will simply be closed, otherwise it will go in for 4.1.
Let me know if my proposal makes sense and if this makes development too complicate on your side

**Comment by keinhaar** [comment]
> if we fix #454 this PR will simply be closed, otherwise it will go in for 4.1.

Makes sense  :-)

**Comment by protoism** [comment]
This PR is a bit obsolete, as lots of dependencies are being removed.
I think that it's possible to remove all file JAR dependencies except gwt of course.

**Comment by protoism** [comment]
Sorry for closing, but this PR is way less relevant now

**Pull request closed without merging**
