### PR TITLE
Eclipse Neon support.

### LINKED ISSUE #139: Support Eclipse Neon June
Start testing on Eclipse Neon.

### LINKED ISSUE #143: Can't install GPE Plugin on a fresh Eclipse NEON installation
When trying to install you always get the error. This is due to the dependency on the compatibility library which my understanding was that it was removed in Mars not sure how I was able to install it in my Mars installation before.

Software being installed: Google Plugin for Eclipse 4.4 0.0.0.201601131605 (com.google.gdt.eclipse.suite.e44.feature.feature.group 0.0.0.201601131605)
  Missing requirement: Google Plugin for Eclipse 4.4 0.0.0.201601131605 (com.google.gdt.eclipse.suite.e44.feature.feature.group 0.0.0.201601131605) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found

### PR DESCRIPTION
**Pull request by axls**
Fix #139, #143.
Plugin org.eclipse.core.runtime.compatibility has been removed from
Eclipse Neon. This patch removes dependency on
org.eclipse.core.runtime.compatibility to be compatible with neon.

### CODE REVIEW

**Comment by ArloL** [comment]
FYI: Neon was released today.

**Comment by axls** [comment]
Experimental build with this fix can be installed from https://dl.bintray.com/axls/gwt-eclipse-plugin.
GWT part works for me, but I'm not sure about AppEngine (never used this one).

**Comment by wbabachan** [comment]
Not working in Eclipse with Gradle. I get the error:

java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class

And I have excluded asm from my projects, specially GIN and Guice...

**Comment by axls** [comment]
@wbabachan 
I'm using gradle too and compilation works fine.
Make sure that incompatible asm is not in eclipse project build path (gwt-dev depends on asm:5.0.3). In eclipse: Navigate -> Open Type... and type `org.objectweb.asm.ClassVisitor`. Then you should see all `asm` artifacts from project build path.
Or, if all gwt-sdk artifacts already in build path (gwt-user, gwt-dev in gradle dependencies), then you can just remove GWT-SDK container from project build path. GPE should detect SDK based on artifacts from build path.

**Comment by branflake2267** [comment]
Sorry for the delay, this is looking good. I'll check this out on Monday and aim to merge it.

**Comment by wbabachan** [comment]
@axis Thanks alot you have right. I have fixed it.

@branflake2267 There is a bug with assiging code server ports, if you set a port unless 9997 Each time if  I open run configuration  it resets to default value.

**Comment by branflake2267** [comment]
I'm digging into what needs to be changed. I've noticed these changes and more.

**Pull request merged**
