### PR TITLE
Fixes #373

### LINKED ISSUE #373: UIBInder validation of super interface methods
If you import the following project into eclipse.
You will see that the ui.xml file contains a validation error when it should not.

https://github.com/seamusmac/gwt-invalid-xml

### PR DESCRIPTION
**Pull request by seamusmac**

### CODE REVIEW

**Comment by seamusmac** [comment]
I fixed the issue with this PR. I am going to test on one of our larger projects now.
If thats ok, I think this is good to merge in :)

**Comment by branflake2267** [comment]
Nice job!

**Comment by branflake2267** [comment]
I'll schedule to do a staging build tomorrow.

**Comment by seamusmac** [comment]
I am not sure, I'm not very experienced in the JDT api, but I moved that down to JLS3 which is java 5, just to be on the safe side. Retested everything and looks good.

**Comment by branflake2267** [comment]
Sounds good. No worries. I see the others are JLS3, do you think you could create a pull for that?

**Comment by seamusmac** [comment]
I already did. See #375 👍

**Pull request merged**
