### PR TITLE
Fix Classic Dev Mode selection on launcher config  for GWT >= 2.7

### PR DESCRIPTION
**Pull request by axls**
I think this PR should fix issue mentioned in https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/61#issuecomment-128171265.

### CODE REVIEW

**Comment by branflake2267** [comment]
I'm pretty sure removing this will break a path or two. What version of GWT is the issue?

**Comment by axls** [comment]
@branflake2267 GWT 2.8-SNAPSHOT. 
Without this PR switching to Classic DevMode does not add "-nosuperDevMode" argument to the program parameters, as well as the application always starts in SuperDev.

In addition, tested with GWT 2.7. It works fine.

**Comment by branflake2267** [comment]
I tried it out and see that it won't set -nosuperDevMode when 2.8.0-SNAPSHOT is selected for the GWT SDK. I'd like to double check the path later today in the dev environment.  Thanks for the details.

**Comment by branflake2267** [comment]
There is a potential workaround if you go straight to the program args tab, add -nosuperDevMode and immediately to debug. As long as it goes straight to debug the validator may not run and then it's just a matter of re-running. I was able to try that and worked for me on the second try.

**Comment by axls** [comment]
Yes, workaround works. Thanks for sharing.

**Comment by branflake2267** [comment]
I'm testing the sdm arg processor. I see a couple broken paths.

**Comment by branflake2267** [comment]
This PR won't fix the issue. I've got a fix in for fixing it and after I go through more testing I'll merge it and get it uploaded. I've got a couple more things to look at before I merge.   https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/89/files

**Comment by branflake2267** [comment]
Just an update. I did some more testing with the changes and it should be fixed in the update. I'll be updating the snapshot build soon and it could be used for testing just to make sure I got it. So far it looks better.

**Pull request closed without merging**
