### PR TITLE
Fixed issue #496 Installation on Eclipse 2024-09

### PR DESCRIPTION
**Pull request by keinhaar**
- Removed the dependency on org.eclipse.jetty.servlet, because it seems to be unnecessary.
- Added gwt 2.10.1 and gwt 2.11.0 to the .gitignore file

### CODE REVIEW

**Comment by keinhaar** [comment]
@protoism would you please check this?

**Comment by protoism** [comment]
Sooner or later we'll have to re-add jetty, as GWT SDK, reasonably, should not be used to serve the application.
But compatibility with 2024-09 is more important...

**Review by protoism — APPROVED** [review]
Of course it's ok....

**Comment by keinhaar** [comment]
> Sooner or later we'll have to re-add jetty, as GWT SDK, reasonably, should not be used to serve the application. But compatibility with 2024-09 is more important...

i do not understand. i did not remove jetty dependency. only jetty.servlet which is no longer present in jetty 12. the devmode with jetty still works normally.

**Pull request merged**
