### PR TITLE
Add oomph setup file

### PR DESCRIPTION
**Pull request by ArloL**
[Oomph](https://projects.eclipse.org/projects/tools.oomph) is an Eclipse project that makes setting up Eclipse installations and workspaces really easy. There is an [Eclipse Installer](http://wiki.eclipse.org/Eclipse_Installer) that you can use. It offers a selection of existing Eclipse.org and GitHub projects. It can install plugins, configure preferences, checkout projects, import projects, etc.

This is an oomph setup file for gwt-eclipse-plugin. I followed the README for the setup. All preferences except for [output filtering](https://github.com/gwt-plugins/gwt-eclipse-plugin#output-filtering) - which I think is unnecessary nowadays - are present.

To test:

1. Download the oomph setup file
2. Download and start the Eclipse Installer
3. Switch to Advanced Mode in the Hamburger menu
4. Select `Eclipse for RCP and RAP Developers` and `Neon`
5. Next
6. Drag and drop the oomph setup file onto GitHub
7. Select `gwt-eclipse-plugin`
8. Next
9. Next
10. Finish
11. Finish and Wait

What you should get is a fully functional Eclipse installation.

Currently I set Luna as the default Target Platform. I am not sure whether this is correct. Mars and Neon are currently supported. There are no repositories configured for Kepler and older.

If the file is merged, you can ask to get it [added to the existing selection of GitHub projects](http://wiki.eclipse.org/Eclipse_Oomph_Authoring#Contributing_to_a_Project_Catalog).

I hope you like it 😄 If there are any questions, let me know!

### CODE REVIEW

**Comment by branflake2267** [comment]
This looks nifty. Looks like this won't add any harm so I'll merge it in a moment. I was just thinking about the platforms, now that neon has been pushed out. I think 3 versions back is probably good enough, so it's probably time to move the target to Kepler. Luna is probably fine for now too. Do you have any preference on targets?

**Comment by ArloL** [comment]
Thanks :) 3 versions sounds reasonable. At work we use Neon and Mars so Luna is fine.

**Comment by ArloL** [comment]
Do you want me to open an issue for adding it to the Project Catalog of the Installer or will you do it?

**Comment by branflake2267** [comment]
Feel free to go for it, I haven't been looking at that. I've been looking into working up a GSS editor.

**Pull request merged**
