### PR TITLE
New target 2022 09

### PR DESCRIPTION
**Pull request by foal**
Support for Eclipse 2022-09 (should be combined with PR #409) + Java 11
Eclipse 2022-09 is minimal due to changes in the m2e integration API

### CODE REVIEW

**Comment by sstamm** [comment]
With GWT 2.10.0 I'm getting: 
```
ENTRY org.eclipse.core.jobs 4 2 2022-11-15 15:26:52.222
!MESSAGE An internal error occurred during: "Validating GWT components".
!STACK 0
java.lang.NoClassDefFoundError: com/google/gwt/dev/util/Empty
	at com.google.gwt.eclipse.core.validators.java.JavaCompilationParticipant$2.acceptAST(JavaCompilationParticipant.java:415)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1008)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:692)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:954)
	at org.eclipse.jdt.internal.corext.dom.ASTBatchParser.createASTs(ASTBatchParser.java:82)
	at com.google.gwt.eclipse.core.validators.java.JavaCompilationParticipant.handleBuildStarting(JavaCompilationParticipant.java:322)
	at com.google.gwt.eclipse.core.validators.java.JavaCompilationParticipant$1.run(JavaCompilationParticipant.java:193)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: com.google.gwt.dev.util.Empty cannot be found by com.gwtplugins.gwt.eclipse.core_3.0.0.202210140533
	... 8 more
```

**Comment by foal** [comment]
I will check.

**Comment by foal** [comment]
Sorry, not yet.

**Comment by niloc132** [comment]
@foal we'd like to get this released, I've made a new PR https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/428 with the changes from three of these other merged into one. Once you take a look and give a +1, we'll merge than, then CI, then change the version in poms to 4.0 and release to the new marketplace site.

If we don't hear from you by beginning of next week, we're going to go ahead and land #428 so we can get working builds out.

**Comment by niloc132** [comment]
Closing, #428 landed this work.

**Pull request closed without merging**
