### PR TITLE
Scrubbing 'Google' from the code and UI

### PR DESCRIPTION
**Pull request by briandealwis**
- [x] _Google GWT_ &rarr; _GWT_
- [x] _Google Web Tools_ &rarr; _GWT Web Tools_
- [x] _Google Eclipse Plugin_ and _Google Plugin for Eclipse_ &rarr; _GWT Eclipse Plugin_
- [x] Strip _Google_ from `Bundle-Name`, `Bundle-Vendor` and `providerName` and use _GWT Project_
- [x] Google_ &rarr; _Gwt_ in class names (e.g., `AbstractGooglePlugin` &rarr; `AbstractGwtPlugin`)
- [x] Get rid of `SelectAppIdDialogTest`
- [x] Expunge `GpeVersionException`-related code (already handled via OSGi's B-REE)
- [x] Expunge Cloud SQL and Cloud Endpoints
- [x] Scrub App Engine, GAE, GPE references as much as possible
- [x] Updated SDBG references and ran integration tests (which pass!)

Punting to another pull:
- [ ] Exorcise or rename `.gcp`: should likely be merged with one of the other testing bundles
- [x] Toss unused `GWTDeploymentParticipant` and `DeploymentParticipantManager` used (the `DeploymentParticipantManager` was invoked as part of the App Engine project deployment)
- [x] Toss `com.gwtplugins.gdt.eclipse.suite.gaeSettingsTab` and friends

Left untouched:
- Kept _Google Inc_ in copyrights
- GWT DTD: `<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit//EN" "http://google-web-toolkit.googlecode.com/svn/trunk/distro-source/core/src/gwt-module.dtd">`

### CODE REVIEW

**Comment by branflake2267** [comment]
nice job!

**Comment by branflake2267** [comment]
It's so nice to have you help get some of this done, thanks!

**Comment by branflake2267** [comment]
When do you think you will get time to finish?

**Comment by briandealwis** [comment]
@branflake2267 It'll be done today.

**Comment by briandealwis** [comment]
Oh, let me merge with HEAD.

**Comment by branflake2267** [comment]
I see you found some issues, thanks for fixing.

**Comment by branflake2267** [comment]
Sorry if I'm creating some conflicts for you. That should be my last merge for a bit. If you want we can merge part way through.

**Comment by briandealwis** [comment]
No worries @branflake2267 — they weren't complicated merges.  PTAL

**Comment by branflake2267** [comment]
Would this be a good place to merge? Or would you rather I wait?

**Comment by branflake2267** [comment]
hm, github auto closed this b/c I merged it into another pr.

**Comment by briandealwis** [comment]
That was a good place to merge: I'm not sure where the `.gcp.eclipse.testing` should be merged to.

**Comment by branflake2267** [comment]
Feel free to do whatever comes to mind and I can re-import it if need be if you do change the naming.

**Comment by branflake2267** [comment]
I think I got stumped on cleaning that a couple times b/c of it's dependencies.

**Pull request merged**
